version: '3'

services: 

  #PHP Services
  firebird_app:
    container_name: firebird_app
    build: 
      context: .
      dockerfile: Dockerfile
    #image: chillytaka/php7.4-firebird
    tty: true
    ports:
      - "8002:80"
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html/
    networks: 
      - app_network


networks: 
  app_network:
    driver: bridge